### ISSUE TITLE
new_file_syntax not working?

### ISSUE THREAD

**Issue by johnathanz** [facelessuser/ApplySyntax#100]
I write a lot in markdown and like all new files opened to be markdown. 

None of these settings (tried individually) seem to work:
> "new_file_syntax": "MarkdownEditing/Markdown",
(MarkdownEditing syntax)

> "new_file_syntax": "Markdown",

> "new_file_syntax": "Markdown/Markdown",

What am I doing wrong?

**Comment by facelessuser** [comment]
This worked for me:

```js
"new_file_syntax": "MarkdownEditing/Markdown",
```

and also this:

```js
"new_file_syntax": "Markdown/Markdown",
```

This will **never** work:

```js
"new_file_syntax": "Markdown",
```

Outside of that, I don't know why it isn't working for you.  There are a lot of assumptions here though:

- I assume you have the appropriate packages installed.
- I assume the appropriate packages are enabled.
- I assume there is nothing wrong with your current install of ApplySyntax.
- I assume ApplySyntax is up to date.
- I assume you aren't seeing errors in your console
- etc.

With what little I have to go on, I would say this works as expected since it works for me.

**Comment by johnathanz** [comment]
I took a video of a few test cases (all with console loaded and applySyntax debug set to "verbose"
1) set "new_file_syntax" to nothing. Start a few new files
2) set "new_file_syntax" to "Markdown/Markdown" (eliminating MarkdownEditing package as a variable). Start a few new files
3) close (all) Sublime window, open a new window
4) close (all) Sublime, quit Sublime, restart

1~3 are on the video: https://vid.me/jG9l

I noticed this:
(i) When the "new_file_syntax" setting is changed, setting woks when opening new file or window
(ii) *Bug:* as soon as a window is closed, or we quit Sublime, we lose the "new_file_syntax". i.e. opening  new file or window
(iii) *Pseudo workaround:* If you open the applySyntax user config file again, the setting works again, until you perform (ii).

It's a weird kind of bug. Or is it one of my settings do you think?

**Comment by facelessuser** [comment]
It looks like a bug in Sublime. Once you've closed the window, and then open a new window, I do see that the setting no longer works, then if I open **any** existing file, suddenly it works again.  I just went into `File->Open Recent` and then picked a random file.  So yes, I see the issue, but I think it is a Sublime issue, not an ApplySyntax issue.  With that said, when I get some time, I want to look into it further to understand what triggers this.

I am curious if this is a recent thing, or an issue that has just gone unnoticed for a while.  I am curious if the `EventListener` Isn't getting created in a new Window until a file that exists on disk is opened or a buffer is saved to disk.

Anyways, it appears it is a real thing.

**Comment by johnathanz** [comment]
thx @facelessuser, thx for investigating this.

I'm new to the Sublime & the ST plugin scene. How did you diagnose this to know it's ST or the plugin?

**Comment by facelessuser** [comment]
> I'm new to the Sublime & the ST plugin scene. How did you diagnose this to know it's ST or the plugin?

Just based on its behavior and how familiar I am with the plugin API.  There was nothing about the situation that screamed there should be some different behavior, but that was what we were seeing.

The actual issue is that on new window creation, with a generic buffer not on disk, `view.settings().get('some_key_that_does_not_exist', 'A default value')` is returning `None`, when you would expect `A default value` to be returned if the key does not exist.  After a new file gets opened, it starts to work as expected.  Weird huh?  I discovered this by simply adding in some print statements detailing the results of reading the setting values.

I can actually work around this, so I can fix it; I'll just restructure my approach on reading the setting.  It's not really a bug in ApplySyntax, but a bug in Sublime, but with a couple of adjustments, I don't think there will be an issue.

**Comment by facelessuser** [comment]
Okay, what its actually happening is view isn't defined (even though a view technically exists or maybe it doesn't until you start typing).  It's weird.  Even if the view doesn't exist, the code still should have worked as we define an empty dict to if we can't acquire a setting object, and both the dict object and the setting object have a `get` method that function the same way...but instead of working proper I get `None`.

Anyways, manually checking if the key exists seems to allow it to work.

**Comment by johnathanz** [comment]
Awesome. Could you please release onto Package Control?  I can bring it
down from there to test.

Thanks for the quick actioning!

**Comment by facelessuser** [comment]
I'll get it out as soon as I can, but I have some stuff I want to take care of first.

**Comment by facelessuser** [comment]
Release made.

**Comment by johnathanz** [comment]
Thanks works perfectly thanks @facelessuser. Is it worth filing a bug at https://github.com/SublimeTextIssues/Core since it's a ST issue?
