### ISSUE TITLE
Path file : Exclude files in subdirectories

### ISSUE THREAD

**Issue by zimxavier** [facelessuser/ApplySyntax#111]
Hi,

I would like to associate files at the root of the folder _countries_ with a syntax file, and files in the subdirectory _flags_ with another one. Unfortunately, I don't master the required syntax and ST load files in _flags_ with the syntax highlighting for _countries_.

Game\common\countries\
- 1 folder: flags
- Some txt files

```
        {
            "syntax": [
                "User/Game_Syntaxes/Game_txt_countries",
            ],
            "rules": [
                {"file_path": ".*\\\\Game\\\\common\\\\countries\\\\.*\\.txt$"}
            ]
        },

        {
            "syntax": [
                "User/Game_Syntaxes/Game_txt_flags",
            ],
            "rules": [
                {"file_path": ".*\\\\Game\\\\common\\\\countries\\\\flags\\\\.*\\.txt$"}
            ]
        },
```
How can I exclude files in subdirectories?

Thank you for your plugin :)
And for any help.

**Comment by zimxavier** [comment]
Hm. I just found the solution, I guess. Sorry.
`
"file_path": ".*\\\\Game\\\\common\\\\countries\\.txt$"`

**Comment by zimxavier** [comment]
It appears I spoke too soon. The syntax highlighting for the files at the root of countries is not loaded. Any help?

**Comment by facelessuser** [comment]
The reason why flags get rendered with countries syntax is because of your regex.  This is not a problem with ApplySyntax.  You have a regex that grabs any file under countries (even files under flags).  And since that rule comes before the flags rule, it will always consume files under flags.

```
{"file_path": ".*\\\\Game\\\\common\\\\countries\\\\.*\\.txt$"}
```

Notice you path uses things like `countries\\\\.*\\.txt` which says you'll take any file under countries.  Even `countries\flags\somefile.txt` because you used `.*` which grabs **any** character. If you used something like `[^\\]*` you would avoid anything under countries with `\` (like folders).

**Comment by zimxavier** [comment]
Apparently, `[^\\]*` doesn't work. `[^\\\\]*` works though:
`{"file_path": ".*\\\\Game\\\\common\\\\countries\\\\[^\\\\]*\\.txt$"}`

Thank you.

**Comment by facelessuser** [comment]
Yeah, sorry. That's what I meant.
