### ISSUE TITLE
Does not work with Sublime Text 3 (build 3059)

### ISSUE THREAD

**Issue by mbrodala** [facelessuser/ApplySyntax#58]
Either I am doing something fundamentally wrong, or this plugin does not work with the lastest stable Sublime Text 3. Neither my custom syntaxes nor the default syntaxes seem to be applied.

For example the INI-Syntax is not applied to Git files, even though I have the corresponding Syntax-Package (clintberry/sublime-text-2-ini) installed.

What might be the issue here?

The only hint I get from Sublime is from the Console:

```
Unable to open /C/Users/<me>/AppData/Roaming/Sublime Text 3/Packages/ApplySyntax/ApplySyntax.sublime-settings
```

**Comment by GoOz** [comment]
@mbrodala Did you ever find the solution? I have the exact same issue. Package installed (multiple times to be sure) with Package Control, ApplySyntax appears in installed package but still the same errors you had.

**Comment by mbrodala** [comment]
Nope, the issue remains and i still have to manually switch syntax for the affected files.

**Comment by KES777** [comment]
I also switch syntax type manually (

**Comment by facelessuser** [comment]
Has anyone tried manually installing ApplySyntax?  The original issue looks to have been throwing an error that only ST2 branch would throw.  But if Package Control is installing the wrong this would circumvent the issue and allow us to verify that the correct branch either causes an issue  or doesn't.  Make sure to uninstall via package control first.

Another issue is that people keep getting confused about how to specify the `name`.  I've recently spent some time updating the docs to make these things more clear http://facelessuser.github.io/ApplySyntax/usage/#name.  Please do read them and let me know if things aren't clear. But `name` requires the relative packages path (`PackageName/sub-directories/if-any/language-file-without-extension`) and file name (extension not needed, and please use forward slashes `/`).

`TypoScript` is not sufficient as it is just pointing at a package directory.  What if two packages have `TypoScript.tmLanguage`?

ApplySyntax used to translate `TypoScript` to `TypoScript/Typoscript`  but that confused people as you could also directly say `TypoScript/Typoscript` .  So now it is always explicit and consistent.

Now that Sublime is adding a new language format, `sublime-syntax` I may make the extension explicit moving forward.

**Comment by mbrodala** [comment]
@facelessuser Thanks for the details, I really appreciate this. Is there some way to debug what syntax was detected or expected? I still have no luck with `TypoScript`, `TypoScript/TypoScript` or `User/TypoScript`. My `TypoScript.tmLanguage` lives in `Packages/User/TypoScript.tmLanguage`.

My latest attempt:

```json
{
  "syntaxes": [
    {
      "name": "TypoScript/Typoscript",
      "rules": [
        {"file_name": ".*(constants|setup)\\.txt$"},
        {"file_name": ".*ext_typoscript_(setup|constants)\\.txt$"}
      ]
    }
  ]
}

```

**Comment by facelessuser** [comment]
If your package lives at `Packages/User/TypoScript.tmLanguage` why are you doing `TypoScript/Typoscript`?  Based on what I mentioned earlier `PackageName/sub-directories/if-any/language-file-without-extension`, you need to do `User/TypoScript`.  Hope that makes sense.

**Comment by mbrodala** [comment]
Because I wanted to be sure to try everything. And as I said `User/TypoScript` doesn't work either.

**Comment by KES777** [comment]
in ApplySyntax.py there is debug( command, but nothing is logged because of 
if no Path continue in 'def set_syntax' also you may set 'dev_enabled' and 'debug_enabled' (I do not remember right, please open ApplySyntax.py and look for 'def debug' 'def devlog'. You can find sharp names there)

Describe in DOC please that
"name": ["RSpec", "RSpec (snippets and syntax)/Syntaxes/RSpec"]
"RSpec" means "Packages/RSpec.tmLanguage"
"RSpec (snippets and syntax)/Syntaxes/RSpec" means "Packages/RSpec (snippets and syntax)/Syntaxes/RSpec.tmLanguage"

You can continue suggestion while name without slash.
So if name : "Perl"
if(  loadresources( 'Packages/Perl.tmLanguage' ); )
  OK
else if( loadresources( 'Packages/Perl/Perl.tmLanguage' ); )
 OK
else
   debug 'No Perl tmLanguage';

**Comment by mbrodala** [comment]
Thanks for the hint to add `debug_enabled` and `dev_enabled` to the user settings. Now I get this on console:

```
ApplySyntax: Language Hash - '8849373952597948661'
ApplySyntax: Updating Extensions
ApplySyntax: Found Extensions: XML/XML - ['xml.dist']
ApplySyntax: Found Extensions: Rails/Ruby Haml - ['haml']
ApplySyntax: Found Extensions: Ruby/Ruby - ['thor', 'rake', 'simplecov', 'jbuilder', 'rb', 'podspec', 'rabl']
ApplySyntax: Found Extensions: Ruby Slim/Syntaxes/Ruby Slim - ['emblem']
ApplySyntax: Found Extensions: Blade/Blade - ['blade.php']
ApplySyntax: Found Extensions: PHP/PHP - ['php3', 'php4', 'php5', 'inc', 'phtml']
ApplySyntax: Found Extensions: PHP/Smarty - ['tpl']
ApplySyntax: Found Extensions: YAML/YAML - ['.gemrc', 'yml', 'yml.dist']
ApplySyntax: Found Extensions: INI/INI - ['.gitattributes', '.gitconfig', '.gitignore', 'ini.dist', '.npmrc']
ApplySyntax: Found Extensions: ShellScript/Shell-Unix-Generic - ['bash', 'sh', 'zsh']
ApplySyntax: Found Extensions: Python/Python - ['py3', 'pyw']
ApplySyntax: Prunning Extensions
```

My TypoScript.tmLanguage is not detected at all even though it was installed as regular package through Package Control and ended up in `Packages/User/`.

Interesting to note that the README of the [TypoScript syntax package](https://packagecontrol.io/packages/TypoScript) now includes this hint for ApplySyntax:

> ## Supported files
> 
> The package will apply the syntax to *.ts files.
> You can create your own rules using the ApplySyntax package with this configuration:
> 
> ```json
> {
>     "syntaxes": [
>         {
>             "name": "TypoScript/TypoScript",
>             "rules": [
>                 {"file_name": ".*\\\\ext_conf_template\\.txt$"},
>                 {"file_name": ".*\\\\ext_typoscript_(setup|constants)\\.txt$"},
>                 {"file_name": ".*\\\\(setup|constants)\\.txt$"}
>             ]
>         }
>     ]
> }
> ```

**Comment by facelessuser** [comment]
The problem I am having is I need to know **exactly** what your setup is.  TypoScript gives an example of what to do, but you have told me that you keep your TypoScript in another location.  I need **excact** info.  Provide me with files and everything I need to know to try and reproduce your situation.

> My TypoScript.tmLanguage is not detected at all even though it was installed as regular package through Package Control and ended up in Packages/User/.

1. That debug info is specifically dealing with the `extensions` keyword in rules.

2. Your rule is using patterns to apply syntax to files named `ext_conf_template.txt`,  `ext_typoscript_setup.txt`, `ext_typoscript_constants.txt`, `setup.txt`, and `constants.txt`.  If you are hoping it will catch `*.ts` files, the rules are not configured to do that, so if that is your problem, you need more rules.

3.  The rules above specifically are for windows paths as they are using backslashes, you may need to add forward slash rules if you are on Linux or OSX.

4. Package Control never installs plugins in `Packages/User`, they are installed in `Packages`, if they are in `User`, then some script has copied them there.  You just mentioned that the TyppoScript plugin specifically tells the user to use the name `TypoScript/TypoScript`, this tells me it isn't supposed to be in `User`.

So I ran a test to since you finally pointed me at the repo you are using for TypoScript.  This is what I did, and these are my results:

1.  Install https://packagecontrol.io/packages/TypoScript via Package Control.  

2.  I added the the `syntaxes` list in my settings file the following rule:

    ```js
    {
            "name": "TypoScript/TypoScript",
            "rules": [
                {"file_name": ".*\\\\ext_conf_template\\.txt$"},
                {"file_name": ".*\\\\ext_typoscript_(setup|constants)\\.txt$"},
                {"file_name": ".*\\\\(setup|constants)\\.txt$"}
            ]
        }
    ```
3. Create a file called `setup.py` on my Desktop.

4.  Open `setup.py` in Sublime Text.

5.  File opened with syntax `TypoScript`

I have no `User/TypoScript.tmLanguage`; neither Package Control or the plugin itself created a file in that location.

This is on Windows7 x64 on Sublime Text Build 3084.

TypoScript and ApplySyntax are working fine for me.  If you want Linux or OSX support either modify paths to use forward slashes or add new rules that use forward slashes under the windows variants.  If you want `*.ts` support, then create a new rule that will trigger on `*.ts` files.

**Comment by facelessuser** [comment]
@KES777 

Please create a separate issue for documentation issues.  I will not address issues that are not in an open, relevant issue.  But thank you for taken time to find some of the inconsistencies.

Documentation is still being improved via issue #72, so there is probably still incorrect info.  If you create an issue, I will correct those mistakes.  For instance, despite what the documentation says, `Rspec` is incorrect.  The actual, official rule does not use that syntax, but uses what I described earlier:

```js
        {
            // One could use just the second rule to match every ruby file in a /spec/
            // directory, but I prefer to be more explicit.
            "name": ["RSpec/RSpec", "RSpec (snippets and syntax)/Syntaxes/RSpec", "Better RSpec/Better RSpec"],
            "rules": [
                {"file_name": ".*spec\\.rb$"},
                {"file_name": ".*/spec/.*\\.rb$"},
                {"file_name": ".*\\\\spec\\\\.*\\.rb$"}
            ]
        },
```

So create a new issue, and I will correct the mistakes.

**Comment by mbrodala** [comment]
@facelessuser Thanks a lot for your info and pointing out my weird `User` path over and over again. Apparently exactly that was the issue; I removed the language file from there and properly installed it via Package Control again. Now it lives in `Installed Packages` and the following setting works:

```json
{
  "syntaxes": [
    {
      "name": "TypoScript/TypoScript",
      "rules": [
        {"file_name": ".*(\\\\|/)ext_conf_template\\.txt$"},
        {"file_name": ".*(\\\\|/)ext_typoscript_(setup|constants)\\.txt$"},
        {"file_name": ".*(\\\\|/)(setup|constants)\\.txt$"}
      ]
    }
  ]
}
```

(Slightly adjusted to support both Windows and Unix paths.)

As for your questions: 2. No, I have manually assigned TypoScript as syntax for `*.ts` files through Sublime.

Once again, thanks a lot. :-)

**Comment by facelessuser** [comment]
> Thanks a lot for your info and pointing out my weird User path over and over again.

I have found learning by repetition very effective :smile:.

I know it took forever to get this resolved for you, but I am glad things are finally working for you.
