### ISSUE TITLE
Keyword is Deprecated

### ISSUE THREAD

**Issue by SecureCloud-biz** [facelessuser/ApplySyntax#81]
In my log, I see this:  **(Please fix ASAP)...**

#### REPRODUCE:
   * i open sublime text 3 [3083] latest,
   * open console, wait for all loading to complete,
   * i have 1 file open a .php file, i hit CTRL+S to Save,
   * i see the following in my console log..

```
ApplySyntax: Warning: 'file_name' keyword is deprecated and may be removed in the future.
ApplySyntax: Syntax already set to Packages/PHP/PHP.tmLanguage
ApplySyntax: Warning: 'name' keyword is deprecated and may be removed in the future.
```
So  <code>'file_name'</code>  and  <code>'name'</code>  got CHANGED or DEPRECATED

Thanks..
:hankey:

**Comment by facelessuser** [comment]
I deprecated it, but they still work as it is only deprecated, not removed.  This is an issue for **you** to fix not me as I am purposefully deprecating it; it was no accident :wink:.

I have changed the names to help with confusion.  I am trying to use names that are a little more clear.  In the future, I **will** remove support for those names, so **you** need to prepare now, which is why I have it warning you.  So, don't freak out, everything is still working, just update your settings accordingly and you will be right as rain.

I know the next question too.  What do you change the names to?  Well, I happened to spend hours writing [documentation](http://facelessuser.github.io/ApplySyntax/usage/), so you should find everything you need there.

**Comment by SecureCloud-biz** [comment]
what the hell are you talking about?
**you 'ARE'** the author of the plug-in, why would it be on **me** to fix this? lol

your plug-in gives an error, you dont want to fix it, then i have an _*easy*_ fix for that..

```
Preferences -> Package Control -> Package Control:Remove Package -> ApplySyntax
```
```
..Removing Package: Apply Syntax
```
```
.. Successfully Removed Package: ApplySyntax
```

I think my way was WAY faster! dont you?

Thanks anyways.  :poop:

**Comment by facelessuser** [comment]
Sigh...

> what the hell are you talking about?
you 'ARE' the author of the plug-in, why would it be on me to fix this? lol

Google deprecation.  Seriously, I think you are greatly misunderstanding what you are seeing.  This is a common programming practice.

> your plug-in gives an error

There are **no errors**. They are warnings that are warning **you** not me.  Because your **personal settings** (that override the repo's) are doing things the old way, **but the plugin is still allowing it**.  It is only **warning** you that in the **future** they will no longer work to give you a transitional period to make sure your personal settings are compliant.

The default settings don't generate warnings because they are compliant with the new way.  If you can show me otherwise, I will fix the global settings, but clearly I can't fix your personal settings that are overriding mine.

> I think my way was WAY faster! dont you?

This is a **free** plugin.  I don't make money off this, but I apparently take flack off people like you.  If your way works for you, I'll sleep tonight.

> Thanks anyways.  :poop:.

Your welcome.
