### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ErnieE5** [facelessuser/ApplySyntax#90]
For **quick** understanding it would be exceptionally useful to have a COMPLETE ApplySyntax.sublime-settings file that had ALL of the possible usage IN the file. (Have one and **I** missed it?)

I **DO** know how to read, but I really just wanted to fix **my** particular annoyance with Sublime, and haven't been able to cobble together the correct syntax (in the time I had).  If I had a FULL example it would likely be an extra simple thing.

Just saying. :-) The fact that you HAVE decent documentation is REALLY nice. But while I **made** time to write this comment, the act of parsing the syntax rules to figure out MY boggle, prevented me from making the fix NOW. 

I am pretty sure that once I have to time to internalize the documentation, it will be obvious. The layout of the project LOOKS 'smart', but the documentation 'suffers' from the 'ya gotta know how to use it to understand it' syndrome. (Me guilty of this too.)

I am certain that this utility will become a 'must install' for me, but for NOW, it is unusable until I sit down with the docs and RTFM.

Thanks for what LOOKS like fine work.

**Comment by ErnieE5** [comment]
And BOOM.  I found what I was looking for. (So much for being in a rush, I think.)  Stupid user trick #2.

**Comment by facelessuser** [comment]
Glad you got it figured out.

I will say in general that 99% of the ways people use ApplySyntax is in the settings file.  There are a couple more costly configurations (scan the whole file etc.) that I generally don't have in the settings file by default because I haven't yet seen a reliable use case that restricts it well enough with appropriate context...though maybe I did pull one recently for Matlab detection...I can't remember.

It is one of those things where we keep it very general which requires more knobs to turn.  To keep it flexible and generic it increases the complexity which in turn increases the learning curve.  We programmers tend to come up with convoluted solutions that make perfect since in our own brains, but not so much in others (or at least I'm guilty of it at times) :smile:.  Hopefully it isn't too bad.  If you do end up having more suggestions to improve it, please feel free to make suggestions or even pull requests.
